export default {
  static: {
    tiles: [
      { type: "solid", x: -5, y: -2 },
      { type: "solid", x: -4, y: -2 },
      { type: "solid", x: -3, y: -2 },
      { type: "solid", x: -2, y: -2 },
      { type: "solid", x: -1, y: -2 },
      { type: "solid", x: 0, y: -2 },
      { type: "solid", x: 1, y: -2 },
      { type: "solid", x: 3, y: -2 },
      { type: "cannon", x: 3, y: -1, dir: "left" },
      { type: "solid", x: 2, y: -2 },
      { type: "solid", x: 4, y: -2 },
      { type: "solid", x: 4, y: -1 },
      { type: "solid", x: 4, y: 0 },
      { type: "solid", x: 4, y: 1 },
      { type: "solid", x: 4, y: 2 },
      { type: "solid", x: 4, y: 3 },
      { type: "lava", x: -6, y: -2 },
      { type: "lava", x: -7, y: -2 },
      { type: "lava", x: -8, y: -2 },
      { type: "solid", x: -9, y: -1 },
      { type: "solid", x: -9, y: -2 },
      { type: "solid", x: -5, y: -1 },
      { type: "solid", x: -5, y: -3 },
      { type: "solid", x: -6, y: -3 },
      { type: "solid", x: -7, y: -3 },
      { type: "solid", x: -8, y: -3 },
      { type: "solid", x: -9, y: -3 },
      { type: "solid", x: -10, y: -2 },
      { type: "solid", x: -11, y: -2 },
      { type: "solid", x: -12, y: -2 },
      { type: "solid", x: -13, y: -2 },
      { type: "solid", x: -14, y: -2 },
      { type: "solid", x: -15, y: -2 },
      { type: "cannon", x: -3, y: 3, dir: "down" },
    ],
  },
};
