export default {
  static: {
    end: { x: 100, y: 100 },
    tiles: [
      { type: "solid", x: -1, y: -1 },
      { type: "solid", x: 0, y: -1 },
      { type: "solid", x: 1, y: -1 },
      { type: "solid", x: -3, y: 5 },
      { type: "solid", x: -3, y: 4 },
      { type: "solid", x: -3, y: 3 },
      { type: "solid", x: -3, y: 2 },
      { type: "solid", x: -3, y: 1 },
      { type: "solid", x: -3, y: 0 },
      { type: "solid", x: -3, y: -1 },
      { type: "solid", x: -2, y: -1 },
      { type: "solid", x: 2, y: -1 },
      { type: "solid", x: 3, y: -1 },
      { type: "solid", x: 4, y: -1 },
      { type: "solid", x: 5, y: -1 },
      { type: "solid", x: 4, y: 0 },
      { type: "lava", x: 5, y: 0 },
      { type: "lava", x: 6, y: 0 },
      { type: "lava", x: 7, y: 0 },
      { type: "lava", x: 8, y: 0 },
      { type: "lava", x: 9, y: 0 },
      { type: "lava", x: 10, y: 0 },
      { type: "solid", x: 6, y: -1 },
      { type: "solid", x: 7, y: -1 },
      { type: "solid", x: 8, y: -1 },
      { type: "solid", x: 9, y: -1 },
      { type: "solid", x: 10, y: -1 },
      { type: "solid", x: 11, y: -1 },
      { type: "solid", x: 11, y: 0 },
      { type: "solid", x: 4, y: 1 },
      { type: "solid", x: 11, y: 1 },
      { type: "interval", x: 6, y: 5, start: "on" },
      { type: "interval", x: 7, y: 5, start: "on" },
      { type: "interval", x: 9, y: 9, start: "off" },
      { type: "interval", x: 8, y: 9, start: "off" },
      { type: "solid", x: 11, y: 2 },
      { type: "solid", x: 11, y: 3 },
      { type: "solid", x: 11, y: 4 },
      { type: "solid", x: 11, y: 5 },
      { type: "solid", x: 11, y: 6 },
      { type: "solid", x: 11, y: 7 },
      { type: "solid", x: 11, y: 8 },
      { type: "solid", x: 11, y: 9 },
      { type: "solid", x: 11, y: 10 },
      { type: "solid", x: 11, y: 11 },
      { type: "interval", x: 6, y: 13, start: "on" },
      { type: "interval", x: 7, y: 13, start: "on" },
      { type: "solid", x: 11, y: 12 },
      { type: "solid", x: 11, y: 13 },
      { type: "solid", x: 11, y: 14 },
      { type: "solid", x: 11, y: 15 },
      { type: "solid", x: 11, y: 16 },
      { type: "solid", x: 11, y: 17 },
      { type: "solid", x: 11, y: 18 },
      { type: "solid", x: 3, y: 16 },
      { type: "solid", x: 2, y: 16 },
      { type: "solid", x: 1, y: 16 },
      { type: "solid", x: 0, y: 16 },
      { type: "solid", x: -1, y: 16 },
      { type: "solid", x: 11, y: 19 },
      { type: "solid", x: 11, y: 20 },
      { type: "solid", x: 11, y: 21 },
      { type: "solid", x: 11, y: 23 },
      { type: "solid", x: 11, y: 22 },
      { type: "cannon", x: 10, y: 17, dir: "left" },
      { type: "solid", x: -2, y: 16 },
      { type: "solid", x: 10, y: 23 },
      { type: "solid", x: 9, y: 23 },
      { type: "solid", x: 8, y: 23 },
      { type: "solid", x: 7, y: 23 },
      { type: "solid", x: 6, y: 23 },
      { type: "solid", x: 5, y: 23 },
      { type: "solid", x: 5, y: 24 },
      { type: "solid", x: 5, y: 25 },
      { type: "solid", x: 5, y: 26 },
      { type: "solid", x: 5, y: 27 },
      { type: "solid", x: 5, y: 28 },
      { type: "solid", x: 5, y: 29 },
      { type: "solid", x: 5, y: 30 },
      { type: "solid", x: 5, y: 32 },
      { type: "solid", x: 5, y: 33 },
      { type: "solid", x: 5, y: 31 },
      { type: "solid", x: -3, y: 16 },
      { type: "solid", x: -4, y: 16 },
      { type: "solid", x: -5, y: 16 },
      { type: "solid", x: -6, y: 16 },
      { type: "solid", x: 2, y: 26 },
      { type: "solid", x: 3, y: 26 },
      { type: "interval", x: -1, y: 29, start: "on" },
      { type: "interval", x: 0, y: 29, start: "on" },
      { type: "solid", x: 5, y: 34 },
      { type: "cannon", x: 4, y: 31, dir: "left" },
      { type: "cannon", x: 4, y: 30, dir: "left" },
      { type: "solid", x: -4, y: 33 },
      { type: "solid", x: -3, y: 33 },
      { type: "interval", x: -1, y: 23, start: "on" },
      { type: "interval", x: 0, y: 23, start: "on" },
      { type: "solid", x: -6, y: 25 },
      { type: "solid", x: -6, y: 24 },
      { type: "solid", x: -6, y: 31 },
      { type: "solid", x: -6, y: 30 },
      { type: "cannon", x: 4, y: 25, dir: "left" },
      { type: "cannon", x: 4, y: 24, dir: "left" },
      { type: "solid", x: -6, y: 17 },
      { type: "solid", x: -6, y: 18 },
      { type: "solid", x: -6, y: 19 },
      { type: "solid", x: -6, y: 20 },
      { type: "solid", x: -6, y: 21 },
      { type: "solid", x: -6, y: 22 },
      { type: "solid", x: -6, y: 23 },
      { type: "solid", x: -6, y: 26 },
      { type: "solid", x: -6, y: 27 },
      { type: "solid", x: -6, y: 28 },
      { type: "solid", x: -6, y: 29 },
      { type: "solid", x: -6, y: 32 },
      { type: "solid", x: -6, y: 33 },
      { type: "solid", x: -6, y: 34 },
      { type: "solid", x: -6, y: 35 },
      { type: "solid", x: -6, y: 36 },
      { type: "solid", x: -6, y: 37 },
      { type: "solid", x: -6, y: 38 },
      { type: "solid", x: -6, y: 39 },
      { type: "solid", x: -6, y: 40 },
      { type: "cannon", x: -5, y: 31, dir: "right" },
      { type: "cannon", x: -5, y: 30, dir: "right" },
      { type: "cannon", x: -5, y: 25, dir: "right" },
      { type: "cannon", x: -5, y: 24, dir: "right" },
      { type: "solid", x: -3, y: 6 },
      { type: "solid", x: -3, y: 7 },
      { type: "solid", x: -3, y: 8 },
      { type: "solid", x: -3, y: 9 },
      { type: "solid", x: -3, y: 10 },
      { type: "solid", x: -3, y: 11 },
      { type: "solid", x: -3, y: 12 },
      { type: "solid", x: -3, y: 13 },
      { type: "solid", x: -3, y: 14 },
      { type: "solid", x: -3, y: 15 },
      { type: "solid", x: 3, y: 17 },
      { type: "solid", x: 3, y: 18 },
      { type: "lava", x: 2, y: 17 },
      { type: "lava", x: 1, y: 17 },
      { type: "lava", x: 0, y: 17 },
      { type: "solid", x: -1, y: 17 },
      { type: "solid", x: -2, y: 17 },
      { type: "solid", x: -3, y: 17 },
      { type: "lava", x: -4, y: 17 },
      { type: "lava", x: -5, y: 17 },
      { type: "cannon", x: 0, y: 33, dir: "up" },
      { type: "cannon", x: 1, y: 33, dir: "up" },
      { type: "solid", x: -5, y: 41 },
      { type: "solid", x: -4, y: 41 },
      { type: "solid", x: -3, y: 41 },
      { type: "solid", x: -2, y: 41 },
      { type: "solid", x: -1, y: 41 },
      { type: "solid", x: 0, y: 41 },
      { type: "solid", x: 1, y: 41 },
      { type: "solid", x: 2, y: 41 },
      { type: "solid", x: 3, y: 41 },
      { type: "solid", x: 4, y: 41 },
      { type: "solid", x: 5, y: 41 },
      { type: "solid", x: -6, y: 41 },
      { type: "cannon", x: 2, y: 33, dir: "up" },
      { type: "solid", x: 6, y: 34 },
      { type: "solid", x: 7, y: 34 },
      { type: "solid", x: 8, y: 34 },
      { type: "solid", x: 9, y: 34 },
      { type: "solid", x: 10, y: 34 },
      { type: "solid", x: 11, y: 34 },
      { type: "solid", x: 12, y: 34 },
      { type: "solid", x: 13, y: 34 },
      { type: "solid", x: 14, y: 34 },
      { type: "solid", x: 4, y: 16 },
      { type: "solid", x: 5, y: 16 },
      { type: "solid", x: -1, y: 18 },
      { type: "solid", x: -2, y: 18 },
      { type: "solid", x: -2, y: 19 },
      { type: "solid", x: -3, y: 20 },
      { type: "solid", x: -3, y: 19 },
      { type: "solid", x: -3, y: 18 },
      { type: "lava", x: 9, y: 35 },
      { type: "lava", x: 9, y: 40 },
      { type: "solid", x: 9, y: 41 },
      { type: "lava", x: 14, y: 36 },
      { type: "lava", x: 14, y: 35 },
      { type: "solid", x: 15, y: 34 },
      { type: "lava", x: 15, y: 35 },
      { type: "lava", x: 15, y: 36 },
      { type: "solid", x: 14, y: 41 },
      { type: "solid", x: 15, y: 41 },
      { type: "lava", x: 10, y: 35 },
      { type: "solid", x: 10, y: 41 },
      { type: "lava", x: 10, y: 40 },
      { type: "solid", x: 6, y: 41 },
      { type: "solid", x: 7, y: 41 },
      { type: "solid", x: 8, y: 41 },
      { type: "solid", x: 11, y: 41 },
      { type: "solid", x: 12, y: 41 },
      { type: "solid", x: 13, y: 41 },
      { type: "solid", x: 16, y: 41 },
      { type: "solid", x: 16, y: 34 },
      { type: "lava", x: 9, y: 39 },
      { type: "lava", x: 10, y: 39 },
      { type: "lava", x: 14, y: 40 },
      { type: "lava", x: 15, y: 40 },
      { type: "solid", x: 17, y: 34 },
      { type: "solid", x: 18, y: 34 },
      { type: "solid", x: 19, y: 34 },
      { type: "solid", x: 20, y: 34 },
      { type: "lava", x: 19, y: 38 },
      { type: "lava", x: 19, y: 39 },
      { type: "lava", x: 19, y: 40 },
      { type: "solid", x: 19, y: 41 },
      { type: "solid", x: 17, y: 41 },
      { type: "solid", x: 18, y: 41 },
      { type: "solid", x: 20, y: 41 },
      { type: "lava", x: 20, y: 40 },
      { type: "lava", x: 20, y: 39 },
      { type: "lava", x: 20, y: 38 },
      { type: "solid", x: 21, y: 34 },
      { type: "solid", x: 22, y: 34 },
      { type: "solid", x: 23, y: 34 },
      { type: "solid", x: 24, y: 34 },
      { type: "solid", x: 25, y: 34 },
      { type: "solid", x: 26, y: 34 },
      { type: "lava", x: 24, y: 35 },
      { type: "lava", x: 24, y: 36 },
      { type: "lava", x: 24, y: 37 },
      { type: "lava", x: 24, y: 38 },
      { type: "lava", x: 25, y: 38 },
      { type: "lava", x: 25, y: 37 },
      { type: "lava", x: 25, y: 36 },
      { type: "lava", x: 25, y: 35 },
      { type: "solid", x: 21, y: 41 },
      { type: "solid", x: 22, y: 41 },
      { type: "solid", x: 23, y: 41 },
      { type: "solid", x: 24, y: 41 },
      { type: "solid", x: 25, y: 41 },
      { type: "solid", x: 26, y: 41 },
      { type: "solid", x: 27, y: 34 },
      { type: "solid", x: 28, y: 34 },
      { type: "solid", x: 29, y: 34 },
      { type: "solid", x: 27, y: 41 },
      { type: "solid", x: 28, y: 41 },
      { type: "solid", x: 29, y: 41 },
      { type: "solid", x: 5, y: 35 },
      { type: "solid", x: 4, y: 35 },
      { type: "solid", x: 6, y: 35 },
      { type: "cannon", x: -1, y: 33, dir: "up" },
      { type: "cannon", x: 29, y: 35, dir: "left" },
      { type: "solid", x: 30, y: 34 },
      { type: "solid", x: 31, y: 34 },
      { type: "solid", x: 32, y: 34 },
      { type: "solid", x: 33, y: 34 },
      { type: "solid", x: 34, y: 34 },
      { type: "solid", x: 35, y: 34 },
      { type: "solid", x: 36, y: 34 },
      { type: "solid", x: 30, y: 41 },
      { type: "solid", x: 30, y: 40 },
      { type: "solid", x: 30, y: 39 },
      { type: "solid", x: 30, y: 38 },
      { type: "solid", x: 30, y: 37 },
      { type: "solid", x: 30, y: 36 },
      { type: "solid", x: 30, y: 35 },
    ],
  },
};
